[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "GET /tasks HTTP/1.1" 500 290
[1m[31mERROR   [0m root:task_utility.py:46 Get the assertion error as, Get task api to show all task created didnt work