[32mINFO    [0m root:task_utility.py:14 Executing create task api
[32mINFO    [0m root:task_utility.py:15 Sending the POST request http://localhost:5000/tasks
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "POST /tasks HTTP/1.1" 200 23
[32mINFO    [0m root:task_utility.py:18 Got the status  code as 200
[32mINFO    [0m root:task_utility.py:24 {'task_id': 'DuiFHjmu'}
[32mINFO    [0m root:task_utility.py:25 Created Task_id is :: DuiFHjmu
[32mINFO    [0m root:test_task_update.py:29 Executing Delete Task API
[32mINFO    [0m root:test_task_update.py:30 Sending the Delete request with task id DuiFHjmu
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "DELETE /tasks/DuiFHjmu HTTP/1.1" 200 23