{"name": "test_incomplete_task_with_invalid_taskid", "status": "failed", "statusDetails": {"message": "AssertionError: Incomplete api with invalid id didn't work\nassert <Response [404]> == ''", "trace": "self = <test_endpoint.test_task_post.TestTaskPost object at 0x000001C80FA18400>\n\n    def test_incomplete_task_with_invalid_taskid(self):\n        logger.info('Executing Incomplete Task API')\n        logger.info('Sending the POST request with task id %s', 123)\n        response = TestTaskPost().incomplete_task_using_invalid_id(123)\n>       assert response == \"\", \"Incomplete api with invalid id didn't work\"\nE       AssertionError: Incomplete api with invalid id didn't work\nE       assert <Response [404]> == ''\n\ntest_task_post.py:42: AssertionError"}, "attachments": [{"name": "log", "source": "6d36c2c4-eb0f-4a6a-8900-49abd2895ade-attachment.txt", "type": "text/plain"}], "start": 1595227598863, "stop": 1595227600887, "uuid": "16792e18-84b6-48c2-ab41-222d210f94ee", "historyId": "20398bb36416d30485b574d8955bd58f", "testCaseId": "0ef4cdfa11bfec4cd3aaa7b3463afc7e", "fullName": "test_endpoint.test_task_post.TestTaskPost#test_incomplete_task_with_invalid_taskid", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('create_and_get_task')"}, {"name": "parentSuite", "value": "test_endpoint"}, {"name": "suite", "value": "test_task_post"}, {"name": "subSuite", "value": "TestTaskPost"}, {"name": "host", "value": "LAPTOP-FMV55K7E"}, {"name": "thread", "value": "9672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_endpoint.test_task_post"}]}