{"name": "test_incomplete_task_with_invalid_taskid", "status": "failed", "statusDetails": {"message": "AssertionError: Incomplete api with invalid id didn't work\nassert '{}' == ''\n  + {}", "trace": "self = <test_endpoint.test_task_post.TestTaskPost object at 0x0000022B035ECB20>\n\n    def test_incomplete_task_with_invalid_taskid(self):\n        logger.info('Executing Incomplete Task API')\n        logger.info('Sending the POST request with task id %s', 123)\n        response = TestTaskPost().incomplete_task_using_invalid_id(123)\n        logger.info(\"Data\", response.text)\n>       assert response.text == \"\", \"Incomplete api with invalid id didn't work\"\nE       AssertionError: Incomplete api with invalid id didn't work\nE       assert '{}' == ''\nE         + {}\n\ntest_task_post.py:43: AssertionError"}, "attachments": [{"name": "log", "source": "bf786626-b1fb-43a6-be93-e6ea61796ba0-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4d83fa45-284a-4dce-bfdb-585438456b0b-attachment.txt", "type": "text/plain"}], "start": 1595227789251, "stop": 1595227791376, "uuid": "830212c0-d0f2-44fc-87a0-efecff733231", "historyId": "20398bb36416d30485b574d8955bd58f", "testCaseId": "0ef4cdfa11bfec4cd3aaa7b3463afc7e", "fullName": "test_endpoint.test_task_post.TestTaskPost#test_incomplete_task_with_invalid_taskid", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('create_and_get_task')"}, {"name": "parentSuite", "value": "test_endpoint"}, {"name": "suite", "value": "test_task_post"}, {"name": "subSuite", "value": "TestTaskPost"}, {"name": "host", "value": "LAPTOP-FMV55K7E"}, {"name": "thread", "value": "16612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_endpoint.test_task_post"}]}